spring:
  application:
    name: voucher

  datasource:
    url: jdbc:postgresql://localhost:5432/seguranalytica
    username: seguranalytica
    password: seguranalytica
    driver-class-name: org.postgresql.Driver

  flyway:
    baseline-on-migrate: true
    schemas: voucher

  jpa:
    properties:
      hibernate:
        default_schema: voucher

springdoc:
  api-docs:
    path: /voucher/api-docs