spring:

  application:
    name: gateway

  cloud:
    discovery:
      locator:
        enabled: true

    gateway:

      routes:

        - id: auth
          uri: http://auth:8080
          predicates:
            - Path=/register/**, /login/**, /auth/**

        - id: account
          uri: http://account:8080
          predicates:
            - Path=/account/**

        - id: data
          uri: http://data:8080
          predicates:
            - Path=/data/**

        - id: voucher
          uri: http://voucher:8080
          predicates:
            - Path=/voucher/**

api:
  endpoints:
    open: >
      POST /register,
      POST /login,
      GET /data/**